version: '3.8'

services:
  postgres:
    image: postgres:12.3
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connect
    ports:
      - "5432:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.9.9-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для RabbitMQ Management Plugin (Web UI)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
